App = require 'app'
{tr} = require 'i18n'

exports.qToQuestion = (q) ->
	if typeof q is 'string'
		tr("Who") + ' ' + q.charAt(0).toLowerCase() + q.slice(1) + '?'

exports.selfRankToText = (nr) ->
	if nr is 1
		tr("1st")
	else if nr is 2
		tr("2nd")
	else if nr is 3
		tr("3rd")
	else if nr is 4 and App.users.count().get() is 4
		tr("4th")
	else if nr is 4
		tr("Middle rank")
	else if nr is 5
		tr("Bottom rank")
	else
		'?'

exports.scoring = -> [10, 4, 1, 0]

# determines duration of the round started at 'currentTime'
exports.getRoundDuration = (currentTime) ->
	return false if !currentTime

	duration = 6*3600 # six hours
	while 22 <= (hrs = (new Date((currentTime+duration)*1000)).getHours()) or hrs <= 9
		duration += 6*3600
		#duration += Math.round(Math.random()*6*3600) # delay randomly

	duration

exports.questions = -> [
	# WARNING: indices are used, so don't remove items from this array (and add new questions at the end)
	# Use null as second array entry if you want to stop a question from being selected (or true if 18+)
	["drinks the most alcohol", null]
	["sleeps the most", null]
	["has had the most bed partners", null]
	["was spoiled as a child", null]
	["makes the most money", null]
	["is the smartest", null]
	["is the fastest in the 100m sprint", null]
	["is easiest to provoke", null]
	["eats the most", null]
	["lives unhealthiest", null]
	["is the funniest", null]
	["is the most charismatic", null]
	["is the most bossy", null]
	["lives the most interesting life", null]
	["does unexpected things", null]
	["is a dreamer", null]
	["should take a bath more often", null]
	["has seen the most movies", null]
	["knows most about sports", null]
	["is an introvert", null]
	["lost his/her virginity the earliest", null]
	["watches most porn", null]
	["is the most optimistic", null]
	["is easiest to embarrass", null]
	["has the best body", null]
	["is the most nerdy", null]
	["dresses best", null]
	["most often helps other people", null]
	["does things without thinking", null]
	["is happiest", null]
	["has the wildest lifestyle", null]
	["talks most", null]
	["listens best", null]
	["has the most energy", null]
	["gossips the most", null]
	["tells the best stories", null]
	["is the best dancer", null]
	["cleans most often", null]
	["would be the first to undergo plastic surgery", null]
	["will live the longest", null]
	["shouts at his/her computer", null]
	["is the most ambitious", null]
	["is the most superstitious", null]
	["is the most eco friendly", null]
	["never talks about feelings", null]
	["weeps most during movies", null]
	["would be the first to go skinny dipping", null]
	["is the most romantic", null]
	["works the hardest", null]
	["is the most creative", null]
	["has read the most books", null]
	["wears the oldest underwear", null]
	["broke the most hearts", null]
	["looks worst after a bad night", null]
	["is the perfect son/daughter-in-law", null]
	["dislikes talking on the phone", null]
	["has the most outspoken opinion", null]
	["would win in a fight", null]
	["has the most bad-hair-days", null]
	["is the best singer", null]
	["is most elitist", null]
	["is least politically correct", null]
	["knows most about sex", null]
	["is the biggest flirt", null]
	["would you trust with your life", null]
	["gets most attention from the opposite sex", null]
	["gets up the earliest", null]
	["could be a pornstar", null]
	["is probably an alien", null]
	["is probably a secret agent", null]
	["might have the most 18+ toys", null]
	["has tried the most drugs", null]
	["is the alpha male/female", null]
	["is a future nobel prize winner", null]
	["has broken the most promises", null]
	["is always late", null]
	["is craziest", null]
	["craves the most attention", null]
	["is the most philosophical", null]
	["will become most famous", null]
	["is the best liar", null]
	["would survive the zombie apocalypse", null]
	["has the most pleasant voice", null]
	["is a hipster", null]
	["is most addicted to his/her phone", null]
	["is the worst driver", null]
	["is most forgetful", null]
	["is the best cook", null]
	["has the worst taste in music", null]
	["spends too much money", null]
	["has travelled the most", null]
	["would make the best salesman", null]
	["types fastest on a phone", null]
	["watches too much TV", null]
	["watches the worst TV shows", null]
	["is clumsiest", null]
	["could seduce anyone", null]
	["has taken nude pictures of him or herself", null]
	["is most likely to have kinky fetishes", null]
	["would pay for sex", null]
	["would be in for a threesome", null]
	["is most bi-curious", null]
	["has the dirtiest mind", null]
	["is most confident", null]
	["gives the most money to charity", null]
	["would be the first to dye his/her hair", null]
	["has probably cheated on exams", null]
	["would be the first to buy a Ferrari", null]
	["looks older than he/she really is", null]
	["can eat without gaining weight", null]
	["is most likely to become a monk/nun", null]
	["would be in for interracial sex", null]
	["could be a time traveller", null]
	["is funniest when drunk", null]
	["is the bravest", null]
	["takes most selfies", null]
	["is always getting into trouble", null]
	["eats junk food most often", null]
	["is most persuasive", null]
	["could be a great actor/actress", null]
	["would have sex on the first date", null]
	["would never harm anyone", null]
	["has the most infectious smile", null]
	["has the most life experience", null]
	["gives the best advice", null]
	["should rule the world", null]
	["has the most beautiful name" ,null]
	["is or would be the best parent", null]
	["laughs most", null]
	["was sent back from the future", null]
	["would have made a great hippy", null]
	["is probably hungover right now", null]
	["has the worst sense of direction", null]
	["secretly reads horoscopes", null]
	["is most addicted to social media", null]
	["is the best public speaker", null]
	["has the biggest vocabulary", null]
	["thinks rules are to be broken", null]
	["should see his/her family more often", null]
	["is/was the teacher’s favourite", null]
	["is most easily stressed", null]
	["is the biggest party animal", null]
	["knows most about celebrity gossip", null]
	["is the master of obscure facts", null]
	["is most dependent upon technology", null]
	["can handle every situation", null]
	["is the best handy(wo)man", null]
	["has most musical talent", null]
	["endlessly postpones tasks", null]
	["enjoys sci-fi most", null]
	["should write a book", null]
	["has the strangest habits", null]
	["has the most tech gadgets", null]
	["is the biggest chickflick-fan", null]
	["knows most plants by name", null]
	["would be the best companion on a deserted island", null]
	["owns most jewelry", null]
	["looks in the mirror most often", null]
	["would be first to sell his/her soul to the devil", null]
	["is most stubborn", null]
	["usually stays until late", null]
	["has the most shoes", null]
	["is the biggest nitpicker", null]
	["is the biggest show-off", null]
	["is the biggest animal lover", null]
	["refuses to deviate from the plan", null]
	["has the most beautiful eyes", null]
	["would be first to get a(nother) tattoo", null]
	["believed in santa clause the longest", null]
	["knows most about cars", null]
	["wears the tightest jeans", null]
	["is the best swimmer", null]
	["likes to annoy people", null]
	["is the most picky eater", null]
	["wears expensive brands", null]
	["uses movie quotes most often", null]
	["would lead the resistance in a war", null]
	["is most in touch with his/her inner child", null]
	["finds it most difficult to say 'no'", null]
	["looks most like a Bond villain", null]
	["sleeps naked", null]
	["has the best reflexes", null]
	["is the most well-connected", null]
	["can be trusted with superpowers", null]
	["is telepathic", null]
	["imagines people naked", null]
	["is loudest", null]
	["believes in life after death", null]
	["is nosiest", null]
	["should buy a new phone", null]
	["gets bored with things quickly", null]
	["is most sophisticated", null]
	["is most conservative", null]
	["is grumpy in the morning", null]
	["would be the best police officer", null]
	["would be happiest as a truck driver", null]
	["wouldn't mind working night shifts", null]
	["might have been an emperor in a previous life", null]
	["doesn't mind doing dirty work", null]
	["would be happiest as a farmer", null]
	["dislikes office jobs most", null]
	["was the most annoying know-it-all as a child", null]
	["is most comfortable wearing high heels", null]
	["would be the best computer programmer", null]
	["is most afraid of heights", null]
	["is most afraid of spiders", null]
	["has the most patience", null]
	["likes Mondays best", null]
	["is most nostalgic", null]
	["has a calming influence on people", null]
	["eats just about anything", null]
	["can be trusted with a big secret", null]
	["has climbed the most trees", null]
	["talks about boobs most often", null]
	["is the biggest Disney fan", null]
	["was/is most popular in school", null]
	["will always want a bigger house", null]
	["is best at solving a rubix cube", null]
	["is the best babysitter", null]
	["is the best text writer", null]
	["is the best at playing pool", null]
	["will be in the history books", null]
	["keeps a baseball bat under the bed", null]
	["swears the most", null]
	["needs the least sleep", null]
	["wanted to be a astronaut when he/she was little", null]
	["has the most secret admirers", null]
	["loves Christmas the most", null]
	["is the biggest daredevil", null]
	["is the best photographer", null]
	["would be the first to buy a hot tub", null]
	["would be the first to buy an electric bicycle", null]
	["is the best snowboarder/skier", null]
	["knows how to dance the Macarena", null]
	["knows how to milk a cow", null]
	["knows how to sail a boat", null]
	["knows how to wield a sword", null]
	["would be first to start a restaurant", null]
	["would be first to start a bed & breakfast", null]
	["would be first to move abroad", null]
	["wears sunglasses indoors to look cool", null]
	["hates rollercoasters the most", null]
	["wishes cell phones were never invented", null]
	["wishes the internet was never invented", null]
	["cares most about Valentine's Day", null]
	["loves Dinh Phi the most", false]
		
	# WARNING: always add new questions to the end of this array
]
